"""
AI Content Filter for SocialKidz
Detects inappropriate content, AI-generated slop, and toxic language
"""

import numpy as np
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
import warnings

warnings.filterwarnings('ignore')

class ContentFilter:
    def __init__(self, config):
        self.config = config
        self.toxicity_threshold = config.TOXICITY_THRESHOLD
        self.slop_threshold = config.SLOP_DETECTION_THRESHOLD
        
        try:
            # Zero-shot classification for content safety
            self.zero_shot_classifier = pipeline(
                "zero-shot-classification",
                model="facebook/bart-large-mnli",
                device=-1  # CPU
            )
        except Exception as e:
            print(f"Warning: Could not load zero-shot classifier: {e}")
            self.zero_shot_classifier = None
        
        try:
            # Toxicity detection
            self.toxicity_classifier = pipeline(
                "text-classification",
                model="michellejieli/NSFW_text_classifier",
                device=-1
            )
        except Exception as e:
            print(f"Warning: Could not load toxicity classifier: {e}")
            self.toxicity_classifier = None
    
    def detect_inappropriate_content(self, text):
        """
        Detects inappropriate content using zero-shot classification
        Returns: (is_inappropriate, confidence_score)
        """
        if not self.zero_shot_classifier or not text:
            return False, 0.0
        
        try:
            inappropriate_labels = [
                "sexual content",
                "violence",
                "hate speech",
                "self-harm",
                "bullying",
                "inappropriate for children",
                "safe and appropriate content"
            ]
            
            result = self.zero_shot_classifier(text, inappropriate_labels)
            
            # If top prediction is "safe", return low score
            if result['labels'][0] == "safe and appropriate content":
                return False, 1.0 - result['scores'][0]
            
            # Otherwise, content is flagged
            confidence = result['scores'][0]
            return confidence > self.toxicity_threshold, confidence
            
        except Exception as e:
            print(f"Error in inappropriate content detection: {e}")
            return False, 0.0
    
    def detect_ai_slop(self, text):
        """
        Detects AI-generated text and low-quality 'slop'
        Returns: (is_slop, confidence_score)
        """
        if not text:
            return False, 0.0
        
        try:
            slop_indicators = [
                "generated by AI",
                "I appreciate your question",
                "I understand your concern",
                "Let me explain",
                "It's important to note",
                "As an AI",
                "Furthermore",
                "In conclusion",
                "Please let me know",
                "Happy to help",
                "I'm here to assist",
                "rest assured",
                "it is crucial",
                "at the end of the day",
            ]
            
            text_lower = text.lower()
            indicator_count = sum(1 for indicator in slop_indicators if indicator.lower() in text_lower)
            
            # Check for repetitive patterns
            words = text.split()
            if len(words) > 0:
                word_freq = {}
                for word in words:
                    word_freq[word.lower()] = word_freq.get(word.lower(), 0) + 1
                
                # If more than 30% of words are repeated
                repeated_word_count = sum(1 for count in word_freq.values() if count > 2)
                repetition_score = repeated_word_count / len(word_freq) if word_freq else 0
            else:
                repetition_score = 0
            
            # Combined score
            slop_score = (indicator_count * 0.1) + (repetition_score * 0.2)
            slop_score = min(1.0, slop_score)  # Cap at 1.0
            
            return slop_score > self.slop_threshold, slop_score
            
        except Exception as e:
            print(f"Error in AI slop detection: {e}")
            return False, 0.0
    
    def detect_toxicity(self, text):
        """
        Detects toxic language
        Returns: (is_toxic, confidence_score)
        """
        if not self.toxicity_classifier or not text:
            return False, 0.0
        
        try:
            result = self.toxicity_classifier(text)
            score = result[0]['score'] if result else 0.0
            
            return score > self.toxicity_threshold, score
            
        except Exception as e:
            print(f"Error in toxicity detection: {e}")
            return False, 0.0
    
    def filter_content(self, text):
        """
        Comprehensive content filtering
        Returns: {
            'is_safe': bool,
            'inappropriate': (bool, score),
            'ai_slop': (bool, score),
            'toxic': (bool, score),
            'overall_score': float,
            'reason': str
        }
        """
        inappropriate, inapp_score = self.detect_inappropriate_content(text)
        ai_slop, slop_score = self.detect_ai_slop(text)
        toxic, tox_score = self.detect_toxicity(text)
        
        reasons = []
        if inappropriate:
            reasons.append("Inappropriate content detected")
        if ai_slop:
            reasons.append("AI-generated content detected")
        if toxic:
            reasons.append("Toxic language detected")
        
        is_safe = not (inappropriate or ai_slop or toxic)
        overall_score = max(inapp_score, slop_score, tox_score)
        
        return {
            'is_safe': is_safe,
            'inappropriate': (inappropriate, inapp_score),
            'ai_slop': (ai_slop, slop_score),
            'toxic': (toxic, tox_score),
            'overall_score': overall_score,
            'reason': ' | '.join(reasons) if reasons else 'Content passed safety checks'
        }
